# Generated by Django 3.0.8 on 2020-07-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20200717_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imgpath',
            field=models.TextField(default='nodata'),
        ),
    ]
