# Generated by Django 3.0.8 on 2020-07-18 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20200717_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='type',
            new_name='t',
        ),
    ]
