# Generated by Django 3.0.8 on 2020-07-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_auto_20200718_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='t',
            new_name='type',
        ),
    ]
