# Generated by Django 3.0.8 on 2020-07-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20200718_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imgpath',
            field=models.CharField(default='nodata', max_length=100),
        ),
    ]
